name: pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools=1.9=ha228f0b_4
  - biopython=1.73
  - bwa=0.7.17=h84994c4_5
  - bz2file=0.98=py_0
  - bzip2=1.0.6=h14c3975_1002
  - ca-certificates=2019.6.16=hecc5488_0
  - certifi=2019.6.16=py37_0
  - curl=7.64.1=hf8cf82a_0
  - decorator=4.4.0=py_0
  - htslib=1.9=ha228f0b_7
  - krb5=1.16.3=h05b26f9_1001
  - ldc=1.10.0=hb2c9046_0
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.64.1=hda55be3_0
  - libdeflate=1.0=h14c3975_1
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran=3.0.0=1
  - liblapack=3.8.0
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - minimap2=2.17=h84994c4_0
  - ncurses=6.1=hf484d3e_1002
  - networkx=2.3=py_0
  - numpy=1.16.4=py37h95a1406_0
  - openblas=0.3.6
  - openssl=1.1.1b=h14c3975_1
  - parallel=20190522=0
  - perl=5.26.2=h516909a_1006
  - pip=18.1=py37_1000
  - pyfaidx=0.5.5.2=py_1
  - pysam=0.15.2=py37h4b7d16d_3
  - python=3.7.1=h381d211_1003
  - pyvcf=0.6.8=py37_1000
  - readline=7.0=hf8c457e_1001
  - sambamba=0.7.0=h89e63da_1
  - samtools=1.9=h8571acd_11
  - seqtk=1.3=h84994c4_1
  - setuptools=41.0.1=py37_0
  - six=1.12.0=py37_1000
  - sqlite=3.28.0=h8b20d00_0
  - tk=8.6.9=hed695b0_1002
  - whatshap=0.18=py37h6bb024c_0
  - wheel=0.33.4=py37_0
  - xopen=0.7.2=py_0
  - xz=5.2.4=h14c3975_1001
  - zlib=1.2.11=h14c3975_1004
  - lastz=1.0.4
  - coreutils=8.25
  - scipy=1.4.1
  - matplotlib=3.1.3

